name: osml-jupyterlab-ext-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - conda-forge::gdal=3.8.3
  - conda-forge::proj=9.3.1
  - jupyterlab=4
  - nodejs=18
  - copier=7
  - jinja2-time
  - git
  - pip
  - pip:
      - osml-imagery-toolkit>=1.4.2
