name: osml-jupyterlab-ext-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12.9
  - conda-forge::gdal=3.8.5
  - conda-forge::proj=9.4.1
  - jupyterlab=4
  - nodejs=18
  - copier=7
  - jinja2-time
  - git
  - pip
  - pip:
      - osml-imagery-toolkit>=1.4.2
      - build
      - twine
      - hatch
