# Copyright Amazon.com, Inc. or its affiliates.

name: osml-jupyterlab-ext-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12.9
  - jupyterlab=4
  - nodejs>=21
  - jinja2-time
  - git
  - pip
  - opencv  # conda-forge opencv avoids macOS _iconv link error from pip wheel
  - pip:
      - osml-imagery-toolkit>=2.0.0a1
      - build
      - twine
      - hatch
