# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.3
_src_path: https://github.com/jupyterlab/extension-template
author_email: aws-osml-admin@amazon.com
author_name: Amazon Web Services
data_format: string
file_extension: ''
has_binder: false
has_settings: true
kind: frontend
labextension_name: osml-jupyter-extension
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension to work with satellite imagery using
    OversightML.
python_name: osml_jupyter_extension
repository: https://github.com/aws-solutions-library-samples/osml-jupyter-extension
test: true
viewer_name: ''

