name: jlpm

on:
  workflow_call:
  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
        lfs: 'true'

    - name: Setup Development Enviornment in Conda 
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: osml-jupyterlab-ext-dev
        environment-file: conda/osml-jupyterlab-ext-dev-environment.yml
        auto-activate-base: false

    - name: Lint the Extension
      run: |
        set -eux
        jlpm
        jlpm run lint:check

    - name: Test Local Install
      run: |
        set -eux
        python -m pip install .[test]
        jlpm run test
        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "osml-jupyter-extension.*OK"
        python -m jupyterlab.browser_check
        