name: pypi

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          lfs: 'true'

      - name: JupyterLab Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install JupyterLab
        run: python -m pip install -U "jupyterlab>=4.0.0,<5"

      - name: Build Package
        run: |
          python -m pip install build
          python -m build

      - uses: pypa/gh-action-pypi-publish@v1.13.0
